// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pb/prophet.proto
#ifndef GRPC_pb_2fprophet_2eproto__INCLUDED
#define GRPC_pb_2fprophet_2eproto__INCLUDED

#include "pb/prophet.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class Prophet final {
 public:
  static constexpr char const* service_full_name() {
    return "Prophet";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status FetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval& request, ::FetchIndicatorResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>> AsyncFetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>>(AsyncFetchStockDateListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>> PrepareAsyncFetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>>(PrepareAsyncFetchStockDateListRaw(context, request, cq));
    }
    virtual ::grpc::Status FetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet& request, ::FetchIndicatorResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>> AsyncFetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>>(AsyncFetchIndicatorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>> PrepareAsyncFetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>>(PrepareAsyncFetchIndicatorRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void FetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval* request, ::FetchIndicatorResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void FetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval* request, ::FetchIndicatorResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void FetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval* request, ::FetchIndicatorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void FetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet* request, ::FetchIndicatorResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void FetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet* request, ::FetchIndicatorResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void FetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet* request, ::FetchIndicatorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>* AsyncFetchStockDateListRaw(::grpc::ClientContext* context, const ::StockDateInterval& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>* PrepareAsyncFetchStockDateListRaw(::grpc::ClientContext* context, const ::StockDateInterval& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>* AsyncFetchIndicatorRaw(::grpc::ClientContext* context, const ::IndicatorSet& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FetchIndicatorResponse>* PrepareAsyncFetchIndicatorRaw(::grpc::ClientContext* context, const ::IndicatorSet& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status FetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval& request, ::FetchIndicatorResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>> AsyncFetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>>(AsyncFetchStockDateListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>> PrepareAsyncFetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>>(PrepareAsyncFetchStockDateListRaw(context, request, cq));
    }
    ::grpc::Status FetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet& request, ::FetchIndicatorResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>> AsyncFetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>>(AsyncFetchIndicatorRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>> PrepareAsyncFetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>>(PrepareAsyncFetchIndicatorRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void FetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval* request, ::FetchIndicatorResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void FetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval* request, ::FetchIndicatorResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void FetchStockDateList(::grpc::ClientContext* context, const ::StockDateInterval* request, ::FetchIndicatorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void FetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet* request, ::FetchIndicatorResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void FetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet* request, ::FetchIndicatorResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void FetchIndicator(::grpc::ClientContext* context, const ::IndicatorSet* request, ::FetchIndicatorResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>* AsyncFetchStockDateListRaw(::grpc::ClientContext* context, const ::StockDateInterval& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>* PrepareAsyncFetchStockDateListRaw(::grpc::ClientContext* context, const ::StockDateInterval& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>* AsyncFetchIndicatorRaw(::grpc::ClientContext* context, const ::IndicatorSet& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FetchIndicatorResponse>* PrepareAsyncFetchIndicatorRaw(::grpc::ClientContext* context, const ::IndicatorSet& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FetchStockDateList_;
    const ::grpc::internal::RpcMethod rpcmethod_FetchIndicator_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status FetchStockDateList(::grpc::ServerContext* context, const ::StockDateInterval* request, ::FetchIndicatorResponse* response);
    virtual ::grpc::Status FetchIndicator(::grpc::ServerContext* context, const ::IndicatorSet* request, ::FetchIndicatorResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_FetchStockDateList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FetchStockDateList() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FetchStockDateList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchStockDateList(::grpc::ServerContext* /*context*/, const ::StockDateInterval* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchStockDateList(::grpc::ServerContext* context, ::StockDateInterval* request, ::grpc::ServerAsyncResponseWriter< ::FetchIndicatorResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FetchIndicator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FetchIndicator() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_FetchIndicator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchIndicator(::grpc::ServerContext* /*context*/, const ::IndicatorSet* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchIndicator(::grpc::ServerContext* context, ::IndicatorSet* request, ::grpc::ServerAsyncResponseWriter< ::FetchIndicatorResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FetchStockDateList<WithAsyncMethod_FetchIndicator<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_FetchStockDateList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_FetchStockDateList() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::StockDateInterval, ::FetchIndicatorResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::StockDateInterval* request, ::FetchIndicatorResponse* response) { return this->FetchStockDateList(context, request, response); }));}
    void SetMessageAllocatorFor_FetchStockDateList(
        ::grpc::experimental::MessageAllocator< ::StockDateInterval, ::FetchIndicatorResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::StockDateInterval, ::FetchIndicatorResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_FetchStockDateList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchStockDateList(::grpc::ServerContext* /*context*/, const ::StockDateInterval* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FetchStockDateList(
      ::grpc::CallbackServerContext* /*context*/, const ::StockDateInterval* /*request*/, ::FetchIndicatorResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FetchStockDateList(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::StockDateInterval* /*request*/, ::FetchIndicatorResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_FetchIndicator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_FetchIndicator() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::IndicatorSet, ::FetchIndicatorResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::IndicatorSet* request, ::FetchIndicatorResponse* response) { return this->FetchIndicator(context, request, response); }));}
    void SetMessageAllocatorFor_FetchIndicator(
        ::grpc::experimental::MessageAllocator< ::IndicatorSet, ::FetchIndicatorResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::IndicatorSet, ::FetchIndicatorResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_FetchIndicator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchIndicator(::grpc::ServerContext* /*context*/, const ::IndicatorSet* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FetchIndicator(
      ::grpc::CallbackServerContext* /*context*/, const ::IndicatorSet* /*request*/, ::FetchIndicatorResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FetchIndicator(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::IndicatorSet* /*request*/, ::FetchIndicatorResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_FetchStockDateList<ExperimentalWithCallbackMethod_FetchIndicator<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_FetchStockDateList<ExperimentalWithCallbackMethod_FetchIndicator<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_FetchStockDateList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FetchStockDateList() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FetchStockDateList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchStockDateList(::grpc::ServerContext* /*context*/, const ::StockDateInterval* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FetchIndicator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FetchIndicator() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_FetchIndicator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchIndicator(::grpc::ServerContext* /*context*/, const ::IndicatorSet* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_FetchStockDateList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FetchStockDateList() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_FetchStockDateList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchStockDateList(::grpc::ServerContext* /*context*/, const ::StockDateInterval* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchStockDateList(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FetchIndicator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FetchIndicator() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_FetchIndicator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchIndicator(::grpc::ServerContext* /*context*/, const ::IndicatorSet* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchIndicator(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_FetchStockDateList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_FetchStockDateList() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FetchStockDateList(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_FetchStockDateList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchStockDateList(::grpc::ServerContext* /*context*/, const ::StockDateInterval* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FetchStockDateList(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FetchStockDateList(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_FetchIndicator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_FetchIndicator() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FetchIndicator(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_FetchIndicator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchIndicator(::grpc::ServerContext* /*context*/, const ::IndicatorSet* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FetchIndicator(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FetchIndicator(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FetchStockDateList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FetchStockDateList() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::StockDateInterval, ::FetchIndicatorResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::StockDateInterval, ::FetchIndicatorResponse>* streamer) {
                       return this->StreamedFetchStockDateList(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FetchStockDateList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FetchStockDateList(::grpc::ServerContext* /*context*/, const ::StockDateInterval* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFetchStockDateList(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::StockDateInterval,::FetchIndicatorResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FetchIndicator : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FetchIndicator() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::IndicatorSet, ::FetchIndicatorResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::IndicatorSet, ::FetchIndicatorResponse>* streamer) {
                       return this->StreamedFetchIndicator(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FetchIndicator() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FetchIndicator(::grpc::ServerContext* /*context*/, const ::IndicatorSet* /*request*/, ::FetchIndicatorResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFetchIndicator(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::IndicatorSet,::FetchIndicatorResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_FetchStockDateList<WithStreamedUnaryMethod_FetchIndicator<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_FetchStockDateList<WithStreamedUnaryMethod_FetchIndicator<Service > > StreamedService;
};


#endif  // GRPC_pb_2fprophet_2eproto__INCLUDED
