# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/common.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/common.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\030com.tigerbrokers.contactB\006CommonP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fpb/common.proto\"@\n\x08\x42\x61seResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\terrorCode\x18\x02 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x03 \x01(\t\"7\n\nResultInfo\x12\x12\n\nerror_code\x18\x01 \x01(\x03\x12\x15\n\rerror_message\x18\x02 \x01(\t*k\n\nERROR_CODE\x12\x16\n\x12\x45RROR_CODE_SUCCESS\x10\x00\x12 \n\x1c\x45RROR_CODE_PARAMETER_INVALID\x10\x01\x12#\n\x1f\x45RROR_CODE_AUTHORIZATION_FAILED\x10\x02*\"\n\tErrorCode\x12\x15\n\x11\x45rrorCode_Unknown\x10\x00*\xa4\x04\n\x0bPORT_DEFINE\x12\x13\n\x0fPORT_DEFINE_NIL\x10\x00\x12\x18\n\x12PORT_DEFINE_TRADER\x10\xe9\x81\x02\x12\x19\n\x13PORT_DEFINE_WX_PUSH\x10\xea\x81\x02\x12\x17\n\x11PORT_DEFINE_GUARD\x10\xeb\x81\x02\x12\"\n\x1cPORT_DEFINE_MARKET_CH_POLICY\x10\xec\x81\x02\x12\x19\n\x13PORT_DEFINE_PROPHET\x10\xed\x81\x02\x12\x1f\n\x19PORT_DEFINE_MARKET_CH_TAG\x10\xee\x81\x02\x12!\n\x1bPORT_DEFINE_PORTFOLIO_STATS\x10\xef\x81\x02\x12\x18\n\x12PORT_DEFINE_XUEQIU\x10\xf0\x81\x02\x12\x1d\n\x17PORT_DEFINE_TEMPORARY_1\x10\xcd\x82\x02\x12\x1d\n\x17PORT_DEFINE_TEMPORARY_2\x10\xce\x82\x02\x12\x1d\n\x17PORT_DEFINE_TEMPORARY_3\x10\xcf\x82\x02\x12\x1d\n\x17PORT_DEFINE_TEMPORARY_4\x10\xd0\x82\x02\x12\x1d\n\x17PORT_DEFINE_TEMPORARY_5\x10\xd1\x82\x02\x12\x1d\n\x17PORT_DEFINE_TEMPORARY_6\x10\xd2\x82\x02\x12\x1d\n\x17PORT_DEFINE_TEMPORARY_7\x10\xd3\x82\x02\x12\x1d\n\x17PORT_DEFINE_TEMPORARY_8\x10\xd4\x82\x02\x12\x1d\n\x17PORT_DEFINE_TEMPORARY_9\x10\xd5\x82\x02*_\n\x0bMARKET_TYPE\x12\x14\n\x10MARKET_TYPE_NONE\x10\x00\x12\x12\n\x0eMARKET_TYPE_CH\x10\x01\x12\x12\n\x0eMARKET_TYPE_HK\x10\x02\x12\x12\n\x0eMARKET_TYPE_US\x10\x03\x42$\n\x18\x63om.tigerbrokers.contactB\x06\x43ommonP\x01\x62\x06proto3'
)

_ERROR_CODE = _descriptor.EnumDescriptor(
  name='ERROR_CODE',
  full_name='ERROR_CODE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR_CODE_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR_CODE_PARAMETER_INVALID', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR_CODE_AUTHORIZATION_FAILED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=142,
  serialized_end=249,
)
_sym_db.RegisterEnumDescriptor(_ERROR_CODE)

ERROR_CODE = enum_type_wrapper.EnumTypeWrapper(_ERROR_CODE)
_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ErrorCode_Unknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=251,
  serialized_end=285,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
_PORT_DEFINE = _descriptor.EnumDescriptor(
  name='PORT_DEFINE',
  full_name='PORT_DEFINE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_NIL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_TRADER', index=1, number=33001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_WX_PUSH', index=2, number=33002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_GUARD', index=3, number=33003,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_MARKET_CH_POLICY', index=4, number=33004,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_PROPHET', index=5, number=33005,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_MARKET_CH_TAG', index=6, number=33006,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_PORTFOLIO_STATS', index=7, number=33007,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_XUEQIU', index=8, number=33008,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_TEMPORARY_1', index=9, number=33101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_TEMPORARY_2', index=10, number=33102,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_TEMPORARY_3', index=11, number=33103,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_TEMPORARY_4', index=12, number=33104,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_TEMPORARY_5', index=13, number=33105,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_TEMPORARY_6', index=14, number=33106,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_TEMPORARY_7', index=15, number=33107,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_TEMPORARY_8', index=16, number=33108,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PORT_DEFINE_TEMPORARY_9', index=17, number=33109,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=288,
  serialized_end=836,
)
_sym_db.RegisterEnumDescriptor(_PORT_DEFINE)

PORT_DEFINE = enum_type_wrapper.EnumTypeWrapper(_PORT_DEFINE)
_MARKET_TYPE = _descriptor.EnumDescriptor(
  name='MARKET_TYPE',
  full_name='MARKET_TYPE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MARKET_TYPE_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MARKET_TYPE_CH', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MARKET_TYPE_HK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MARKET_TYPE_US', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=838,
  serialized_end=933,
)
_sym_db.RegisterEnumDescriptor(_MARKET_TYPE)

MARKET_TYPE = enum_type_wrapper.EnumTypeWrapper(_MARKET_TYPE)
ERROR_CODE_SUCCESS = 0
ERROR_CODE_PARAMETER_INVALID = 1
ERROR_CODE_AUTHORIZATION_FAILED = 2
ErrorCode_Unknown = 0
PORT_DEFINE_NIL = 0
PORT_DEFINE_TRADER = 33001
PORT_DEFINE_WX_PUSH = 33002
PORT_DEFINE_GUARD = 33003
PORT_DEFINE_MARKET_CH_POLICY = 33004
PORT_DEFINE_PROPHET = 33005
PORT_DEFINE_MARKET_CH_TAG = 33006
PORT_DEFINE_PORTFOLIO_STATS = 33007
PORT_DEFINE_XUEQIU = 33008
PORT_DEFINE_TEMPORARY_1 = 33101
PORT_DEFINE_TEMPORARY_2 = 33102
PORT_DEFINE_TEMPORARY_3 = 33103
PORT_DEFINE_TEMPORARY_4 = 33104
PORT_DEFINE_TEMPORARY_5 = 33105
PORT_DEFINE_TEMPORARY_6 = 33106
PORT_DEFINE_TEMPORARY_7 = 33107
PORT_DEFINE_TEMPORARY_8 = 33108
PORT_DEFINE_TEMPORARY_9 = 33109
MARKET_TYPE_NONE = 0
MARKET_TYPE_CH = 1
MARKET_TYPE_HK = 2
MARKET_TYPE_US = 3



_BASERESP = _descriptor.Descriptor(
  name='BaseResp',
  full_name='BaseResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='BaseResp.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='BaseResp.errorCode', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorMsg', full_name='BaseResp.errorMsg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=83,
)


_RESULTINFO = _descriptor.Descriptor(
  name='ResultInfo',
  full_name='ResultInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='ResultInfo.error_code', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='ResultInfo.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['BaseResp'] = _BASERESP
DESCRIPTOR.message_types_by_name['ResultInfo'] = _RESULTINFO
DESCRIPTOR.enum_types_by_name['ERROR_CODE'] = _ERROR_CODE
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
DESCRIPTOR.enum_types_by_name['PORT_DEFINE'] = _PORT_DEFINE
DESCRIPTOR.enum_types_by_name['MARKET_TYPE'] = _MARKET_TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaseResp = _reflection.GeneratedProtocolMessageType('BaseResp', (_message.Message,), {
  'DESCRIPTOR' : _BASERESP,
  '__module__' : 'pb.common_pb2'
  # @@protoc_insertion_point(class_scope:BaseResp)
  })
_sym_db.RegisterMessage(BaseResp)

ResultInfo = _reflection.GeneratedProtocolMessageType('ResultInfo', (_message.Message,), {
  'DESCRIPTOR' : _RESULTINFO,
  '__module__' : 'pb.common_pb2'
  # @@protoc_insertion_point(class_scope:ResultInfo)
  })
_sym_db.RegisterMessage(ResultInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
